version: '3'

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=taxi-db
      - MONGO_INITDB_USERNAME=root
      - MONGO_INITDB_PASSWORD=root
    volumes:
      - ./_data/mongo:/data/db
      - ./docker/_mongo/fixtures:/import
      - ./docker/_mongo/scripts/init.sh:/docker-entrypoint-initdb.d/setup.sh
    ports:
      - '27017:27017'
    networks:
      - kafka-net

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3222:3222
    depends_on:
      - mongo
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run server
    networks:
      - kafka-net

networks:
  kafka-net:
    external: true